  (defun color-theme-anb-dark ()
    (interactive)
    (color-theme-install
     '(color-theme-anb-dark
       ((foreground-color . "#DDDDDD")
        (background-color . "#202020")
        (background-mode . light)
        (cursor-color . "#444444"))
       (bold ((t (:bold t))))
       (bold-italic ((t (:italic t :bold t))))
       (default ((t (nil))))
       (font-lock-builtin-face ((t (:italic t :foreground "#a96da0"))))
       (font-lock-comment-face ((t (:italic t :foreground "#666666"))))
       (font-lock-comment-delimiter-face ((t (:foreground "#666666"))))
       (font-lock-constant-face ((t (:bold t :foreground "#197b6e"))))
       (font-lock-doc-string-face ((t (:foreground "#666666"))))
       (font-lock-doc-face ((t (:foreground "#666666"))))
       (font-lock-reference-face ((t (:foreground "white"))))
       (font-lock-function-name-face ((t (:foreground "#883333"))))
       (font-lock-keyword-face ((t (:bold t :foreground "#bb4400"))))
       (font-lock-preprocessor-face ((t (:foreground "#e3ea94"))))
       (font-lock-string-face ((t (:foreground "#33CC44"))))
       (font-lock-type-face ((t (:bold t :foreground "#888822"))))
       (font-lock-variable-name-face ((t (:foreground "#2070B8"))))
       (font-lock-warning-face ((t (:bold t :italic nil :underline nil :background "#AA0000"))))
       (hl-line ((t (:foreground nil :background "#000000"))))
       (mode-line ((t (:foreground "#ffffff" :background "#333333"))))
       (mode-line-highlight ((t (:foreground "#cc5500" :background "#333333"))))
       (mode-line-inactive ((t (:foreground "#bbbbbb" :background "#111111"))))
       (region ((t (:foreground nil :background "#333333"))))
       (isearch ((t (:bold t :background "#163B65" :foreground "#FFFF00"))))
       (isearch-lazy-highlight-face ((t (:background "#163B65" :foreground "#FFFFFF"))))
       (ido-first-match ((t (:foreground "#eeee33"))))
       (ido-only-match ((t (:foreground "#cc5500"))))
       (w3m-anchor-face ((t (:foreground "#803A00"))))
       (w3m-arrived-anchor-face ((t (:foreground "#501A00"))))
       (w3m-header-line-location-content-face ((t (:background "#0F0F0F"))))
       (w3m-header-line-location-title-face ((t (:background "#000000"))))
       (ascii-non-ascii-face ((t (:background "#FFFF00"))))
       (diff-added ((t (:foreground "#559944"))))
       (diff-removed ((t (:foreground "#de1923"))))
       (diff-context ((t nil)))
       (diff-function ((t (:background "#101010") (:foreground "#00bbdd"))))
       (diff-file-header ((t (:background "#335577"))))
       (diff-header ((t (:background "#335577"))))
       (diff-hunk-header ((t (:foreground "#eeee33")))) ; fbde2d
       (diff-nonexistent ((t (:inherit diff-file-header :strike-through nil))))
       (diff-refine-change ((((class color) (min-colors 88) (background dark)) (:background "#182042"))))
       (mumamo-background-chunk-major ((f nil)))
       (mumamo-background-chunk-submode1 ((((class color) (min-colors 88) (background dark)) (:background "#102020"))))
       (mumamo-background-chunk-submode2 ((((class color) (min-colors 88) (background dark)) (:background "#102020"))))
       (mumamo-background-chunk-submode3 ((((class color) (min-colors 88) (background dark)) (:background "#102020"))))
       (mumamo-background-chunk-submode4 ((((class color) (min-colors 88) (background dark)) (:background "#201010"))))
       (minibuffer-prompt ((t (:foreground "#2070B8"))))
       (erc-prompt-face ((t (:bolt t :foreground "#ffffff" :background "#116611"))))
       ;; (erc-current-nick-face ((t (:bold t :foreground "yellow" :weight bold))))
       ;; (erc-default-face ((t (nil))))
       ;; (erc-direct-msg-face ((t (:foreground "pale green"))))
       ;; (erc-error-face ((t (:bold t :foreground "IndianRed" :weight bold))))
       ;; (erc-highlight-face ((t (:bold t :foreground "pale green" :weight bold))))
       ;; (erc-input-face ((t (:foreground "light blue"))))
       ;; (erc-inverse-face ((t (:background "steel blue"))))
       ;; (erc-notice-face ((t (:foreground "light salmon"))))
       ;; (erc-pal-face ((t (:foreground "pale green"))))
       ;; (erc-prompt-face ((t (:bold t :foreground "light blue" :weight bold))))
       ;; (erc-underline-face ((t (:underline t))))
       (twitter-header-face ((t (:background "#0F0F0F"))))
       (twitter-user-name-face ((t (:background "#0F0F0F"))))
       (twitter-time-stamp-face ((t (:background "#0F0F0F"))))
       (twitter-status-overlong-face ((t (:background "#0F0F0F"))))
       (twitter-new-tweets-sep-face ((t (:background "#0F0F0F"))))
       (show-paren-match-face ((t (:bold t :foreground "#ffffff"
                                         :background "#050505")))))))
(provide 'color-theme-anb-dark)
